# Generated by Django 3.0.1 on 2020-01-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200107_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='fires',
            field=models.ManyToManyField(to='api.Fire'),
        ),
    ]
