# Generated by Django 3.0.1 on 2020-01-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_truck_fires'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
