# Generated by Django 3.0.1 on 2020-01-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200107_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='name',
        ),
    ]
